- name: BCM Ansible module Demo
  hosts: bcm
  collections:
    - brightcomputing.bcm100
  gather_facts: false
  tasks:
    - name: Mount an NFS share to FS mount in a Category
      category:
        name: "login-node"
        fsmounts:
          - device: "10.245.100.140:/zstest1"
            mountpoint: "/mnt/zstest1"
            filesystem: "nfs"
            mountoptions: defaults
            dump: false
            extra_values: null
            fsck: NONE
            rdma: false
